chartToUpdate:
  projectId: 86061211
  projectName: yadokari-smoke-test-chart
  mrTargetBranch: main
appSpecs:
  - projectId: 82861978
    projectName: sample-qa-sprint
    tagFormat: "{branch}-build-at-{date}-{time}"
  - projectId: 82861977
    projectName: sample-develop-client
    tagFormat: "{branch}-build-at-{date}-{time}"
