helm:
  chart: # Helmの向き先ブランチの書き込み先
    - valuesPath: charts/my-app/values.yaml
      anchor: myAppTargetBranch
    - valuesPath: charts/another-app/values.yaml
      anchor: anotherAppTargetBranch
    - valuesPath: charts/multi-service-app/values.yaml
      anchor: multiServiceAppTargetBranch
apps:
  - projectId: 888 # config.yaml と一致させる
    projectName: my-app # config.yaml と一致させる
    chart:
      - valuesPath: charts/my-app/values.yaml
        anchor: myAppVersion # values.yaml内のYAMLアンカー名
  - projectId: 889
    projectName: another-app
    chart:
      - valuesPath: charts/another-app/values.yaml
        anchor: tenantId1client1AppsVersion
  - projectId: 890
    projectName: multi-service-app
    chart:
      - valuesPath: charts/multi-service-app/values.yaml
        anchor: multiServiceAppWebapiVersion
      - valuesPath: charts/multi-service-app/values.yaml
        anchor: multiServiceAppBatchVersion
      - valuesPath: charts/multi-service-app/values.yaml
        anchor: multiServiceAppDaemonVersion
